---
title: "Final_Olympics"
format: html
editor: visual
table-caption: true
---

```{r}
#uploading code#
olympics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-08-06/olympics.csv')

#adding associated packages#
library(tidyverse)
library(gtsummary)
library(broom)
```

1.  This data this comes from the RGriffin Kaggle dataset which is basic bio data on athletes and medal results from Athens 1896 to Rio 2016.

```{r}
#creating a table using gtsummary#

#| label: tbl-descr
#| tbl-cap: "Descriptive Statistics"
knitr::kable(olympics)

tbl_summary(
	olympics,
	by = year,
	include = c(year, weight, height
	)
)
```

```{r}
# fit a univariate regression#

#| label: tbl-reg
#| tbl-cap: "Univariate Regression of year on other variables"

	tbl_uvregression(
		olympics,
		y = year,
		include = c(
			 medal,weight,height
		),
		method = lm
	)
```

```{r}

#create a figure

#| label: fig-hist
#| fig-cap: "Histogram of Athlete's Ages"

hist(olympics$age)


```

@tbl-descr contains a table and @fig-hist a histogram.

```{r}

stats <- list(n = nrow(olympics),
							mean_height = mean(olympics$height, na.rm = TRUE))

print(stats)

```
2. There were `r stats$n` athletes. 
3. The mean height of the athletes was `r mean(olympics$height)`
